# 01c -- dim_fantasy_teams Seed

**Purpose**: Build `dim_fantasy_teams` from the league's Google Sheet owner registry.
The sheet is the single source of truth for team names, abbreviations, and
manager contacts.

**Key**: `team_key` (matches Google Sheet "Team ID" column: A01-A14, B01-B14)

**Source**: Google Sheet — must be set to "Anyone with the link can view"

**Divisions → Conferences**:
- Riddell → A (A01–A14)
- Wilson  → B (B01–B14)

**Cap columns**: this table only carries the two cap facts that are true
independent of the roster -- `original_cap` (`CFG.total_cap`, never changes)
and `reinvestment_cap` (in-season bonus cap charges, 0 at seed time).
Everything roster-derived (active roster salary, dead money, remaining cap)
used to be an ETL rollup cached here (02e); it's now computed live instead
-- from `Fact_FantasyTeams` via the `_Measures.tmdl` DAX measures in Power
BI, and from `fact_fantasy_teams.parquet` via `discord_bot/capmath.py` in
the bot. One formula, not a third cached copy.

**Outputs**:
- `data/dim_fantasy_teams.parquet`

In [1]:
# ---- Setup & Config (shared module) ----------------------------------------
# All config + path anchoring + helpers live in notebooks/etl_helpers.py.
# CFG.data_dir / DATA / REVIEW are anchored to the repo root -> writes always
# land in <repo>/data no matter the CWD this notebook runs from.
import sys
from pathlib import Path
for _p in (Path.cwd() / "notebooks", Path.cwd(), Path.cwd().parent):
    if (_p / "etl_helpers.py").exists():
        sys.path.insert(0, str(_p)); break
import etl_helpers as etl
from etl_helpers import (LeagueConfig, CFG, DATA, REVIEW, TODAY, ALIAS,
                         clean_player_name, generate_player_key, parse_height_to_inches)

import pandas as pd
import numpy as np
import requests
from pathlib import Path
from datetime import date
from dataclasses import dataclass, field

## 1 -- Load from Google Sheet

Re-run this notebook any time team names or manager emails change in the sheet.

In [2]:
# -- Pull team registry from Google Sheet ------------------------------------
# Sheet must be set to "Anyone with the link can view".
# pd.read_csv follows redirects automatically via urllib.
print(f"Loading team sheet: {CFG.team_sheet_csv_url}")
try:
    teams_raw = pd.read_csv(CFG.team_sheet_csv_url)
except Exception as e:
    raise RuntimeError(
        f"Failed to load team sheet. Confirm sheet is publicly viewable.\n{e}"
    ) from e

print(f"Rows loaded : {len(teams_raw)}")
print(f"Columns     : {list(teams_raw.columns)}")
teams_raw

Loading team sheet: https://docs.google.com/spreadsheets/d/1Fiz_KHH5bexSAHIfL0uVIqgHU6jTgnOmDs86kjR8TZc/export?format=csv&gid=178660131

Rows loaded : 28
Columns     : ['Division', 'Team Name', 'Team Abbreviation', 'Manager Email', 'Other Manager Email', 'Team ID', 'Fantrax-TeamId']

,Division,Team Name,Team Abbreviation,Manager Email,Other Manager Email,Team ID,Fantrax-TeamId
0,Riddell,"""National Anthem"" (R)",DegenMik,mvreeland6@gmail.com,NaN,A09,4uapm6ktmo32bach
1,Riddell,AC/DeeCeedeez Nuts (R),tempfool,juventude85@yahoo.com,NaN,A01,cw1na7n0moq8y8sq
2,Riddell,Big L (R),BIGL,benjaninja77@gmail.com,NaN,A10,pyjz79zdmn0kbl9b
3,Wilson,Black Magic Woman (W),BMW,justinacain24@gmail.com,NaN,B01,b3l7iznmmoboq9lg
4,Riddell,Brantley Gilbert (R),Thebusdr,j.milakovich@yahoo.com,NaN,A08,1vtj2q04mnax2yvd
5,Wilson,Bush (W),NT 7,jakeleer@icloud.com,NaN,B02,koqir027mo31l0cn
6,Riddell,Cyndi Lauper (R),NT 5,davismelanie1999@gmail.com,NaN,A02,ru6p9h06mo31l0c7
7,Wilson,Eminem (W),Shady,Valkyn KynVal,NaN,B06,s5bodsc1mn6pjqtc
8,Riddell,Flava Flav (R),Bjuenger,brenden.juengert@gmail.com,NaN,A03,oux5mrxgmn1ujei0
9,Wilson,Franz Ferdinand (W),FF,eduardo.ruizsanz@gmx.com,NaN,B05,cyq413lymnum51np
10,Wilson,J Cole (W),BGFH,benjaninja77@gmail.com,NaN,B03,s6y6g0eamo6p5bqg
11,Riddell,JETHRO TULL (R),Thehardw,travnjazz1221@gmail.com,NaN,A04,evco1hwimmvjr0co
12,Riddell,Kid Rock (R),K.R.,ray_jay@aol.com,NaN,A05,fv4f0av3mo4tgzqw
13,Riddell,Led Zeppelin (R),Bob 2,kannall73@gmail.com,NaN,A06,vvqisetnmn0kbl9q
14,Wilson,Lynyrd Skynyrd (W),Bob,kannall73@gmail.com,NaN,B08,6nhnbkuqmmwi166w
15,Riddell,Meat Loaf (R),Loaf,blord20@gmail.com,NaN,A07,f21lzl7xmn0kdqo8
16,Wilson,Meatloaf (W),NT 20,blord20@gmail.com,NaN,B09,66ao8djmmn0kdqp0
17,Wilson,Notorious (W),TheChair,troyad699@gmail.com,troyadavis2019@hotmail.com,B10,brkcyuhbmmyzna5f
18,Wilson,Post Malone (W),NT 8,sergiomiranda78@gmail.com,NaN,B12,i0bvcjk8mo31l0cs
19,Wilson,Run DMC (W),DMC,npascucci23@gmail.com,NaN,B11,6wmapyeymntmhosz
20,Wilson,Shredding Terry Kath (W),STK,lecroy_57@yahoo.com,NaN,B07,iud32x7mmpj9c9ev
21,Riddell,Spice Girls (R),jordansh,jordanshutta@gmail.com,NaN,A11,v1xh8wzxmn59uqpa
22,Wilson,Steel Panther (W),NT 10,jnjwuerl@gmail.com,NaN,B13,886rcw25mo31l0cy
23,Wilson,Sting and the CeeDees (W),STCD,juventude85@yahoo.com,NaN,B04,va7pi5bimocarcvi
24,Wilson,Brooks and Dunn (W),BD,j.milakovich@yahoo.com,NaN,B14,mvg3okqimod4pn38
25,Riddell,Swishahouse (R),KOOPA,lukeep@gmail.com,NaN,A12,j9reafynmn0kbl9m
26,Riddell,The Skattmen (R),TSM,thejaninator4991@gmail.com,frigidaire77@gmail.com,A13,bj0zd16smn1ssf8h
27,Riddell,Wu-Tang Protection (R),WTP,ty.mcfadden0692@gmail.com,NaN,A14,rzhahbekmmzbhdoj

## 2 -- Build dim_fantasy_teams

In [3]:
# -- Column map: sheet -> dim_fantasy_teams -------------------------------------------
# Sheet columns: Division, Team ID, Team Name, Team Abbreviation,
#                Manager Email, Other Manager Email, Fantrax-TeamId
# Fantrax-TeamId is the league's authoritative teamId<->team_key identity
# (ADR-0005 locked column). Carrying it here lights up the ADR-0004 ledger join
# (teamId -> team_key in 02d) directly, retiring the name-match heuristic crosswalk.
_COL_MAP = {
    "Team ID":              "team_key",
    "Team Name":            "team_name",
    "Team Abbreviation":    "team_abbr",
    "Fantrax-TeamId":       "fantrax_team_id",
    "Division":             "division",
    "Manager Email":        "manager_email",
    "Other Manager Email":  "manager_email_2",
}

# Division -> conference letter (Riddell = A, Wilson = B)
_DIV_CONF = {"Riddell": "A", "Wilson": "B"}


def build_dim_fantasy_teams(raw: pd.DataFrame, cfg: LeagueConfig) -> pd.DataFrame:
    # Validate expected columns
    missing = [c for c in _COL_MAP if c not in raw.columns]
    if missing:
        raise ValueError(f"Sheet missing expected columns: {missing}")

    df = raw.rename(columns=_COL_MAP).copy()

    # Derive conference from division
    df["conference"] = df["division"].map(_DIV_CONF)
    unmapped_divs = df[df["conference"].isna()]["division"].unique()
    if len(unmapped_divs):
        raise ValueError(f"Unknown divisions -- add to _DIV_CONF: {list(unmapped_divs)}")

    # Normalise nullable email column
    df["manager_email_2"] = df["manager_email_2"].where(df["manager_email_2"].notna(), other=pd.NA)

    # Fantrax-TeamId must be present + unique (it's the ledger identity key).
    if df["fantrax_team_id"].isna().any():
        raise ValueError(
            f"Blank Fantrax-TeamId for: {list(df.loc[df['fantrax_team_id'].isna(), 'team_key'])}")
    if not df["fantrax_team_id"].is_unique:
        raise ValueError("Fantrax-TeamId values are not unique")

    # -- Cap state columns ---------------------------------------------------
    # original_cap/reinvestment_cap are the only true team-level cap facts --
    # everything roster-derived (active salary, dead money, remaining cap) is
    # computed live from fact_fantasy_teams instead of cached here (matches
    # the Power BI measures in _Measures.tmdl; see discord_bot/capmath.py for
    # the bot's live equivalent). 02e no longer rolls anything up into this
    # table.
    df["original_cap"]      = cfg.total_cap
    df["reinvestment_cap"]  = 0

    # -- Final column order -----------------------------------------------
    cols = [
        "team_key", "team_name", "team_abbr", "fantrax_team_id",
        "conference", "division",
        "manager_email", "manager_email_2",
        "original_cap", "reinvestment_cap",
    ]
    return df[cols].reset_index(drop=True)


dim_fantasy_teams = build_dim_fantasy_teams(teams_raw, CFG)

out_path = DATA / "dim_fantasy_teams.parquet"
dim_fantasy_teams.to_parquet(out_path, index=False)
print(f"dim_fantasy_teams: {len(dim_fantasy_teams)} teams -> {out_path}")
dim_fantasy_teams

dim_fantasy_teams: 28 teams -> C:\Users\benha\OneDrive\Documents\GitHub\Python-PowerBI-DynastyFantasyFootball\data\dim_fantasy_teams.parquet

,team_key,team_name,team_abbr,fantrax_team_id,conference,division,manager_email,manager_email_2,original_cap,reinvestment_cap
0,A09,"""National Anthem"" (R)",DegenMik,4uapm6ktmo32bach,A,Riddell,mvreeland6@gmail.com,NaN,300000000,0
1,A01,AC/DeeCeedeez Nuts (R),tempfool,cw1na7n0moq8y8sq,A,Riddell,juventude85@yahoo.com,NaN,300000000,0
2,A10,Big L (R),BIGL,pyjz79zdmn0kbl9b,A,Riddell,benjaninja77@gmail.com,NaN,300000000,0
3,B01,Black Magic Woman (W),BMW,b3l7iznmmoboq9lg,B,Wilson,justinacain24@gmail.com,NaN,300000000,0
4,A08,Brantley Gilbert (R),Thebusdr,1vtj2q04mnax2yvd,A,Riddell,j.milakovich@yahoo.com,NaN,300000000,0
5,B02,Bush (W),NT 7,koqir027mo31l0cn,B,Wilson,jakeleer@icloud.com,NaN,300000000,0
6,A02,Cyndi Lauper (R),NT 5,ru6p9h06mo31l0c7,A,Riddell,davismelanie1999@gmail.com,NaN,300000000,0
7,B06,Eminem (W),Shady,s5bodsc1mn6pjqtc,B,Wilson,Valkyn KynVal,NaN,300000000,0
8,A03,Flava Flav (R),Bjuenger,oux5mrxgmn1ujei0,A,Riddell,brenden.juengert@gmail.com,NaN,300000000,0
9,B05,Franz Ferdinand (W),FF,cyq413lymnum51np,B,Wilson,eduardo.ruizsanz@gmx.com,NaN,300000000,0
10,B03,J Cole (W),BGFH,s6y6g0eamo6p5bqg,B,Wilson,benjaninja77@gmail.com,NaN,300000000,0
11,A04,JETHRO TULL (R),Thehardw,evco1hwimmvjr0co,A,Riddell,travnjazz1221@gmail.com,NaN,300000000,0
12,A05,Kid Rock (R),K.R.,fv4f0av3mo4tgzqw,A,Riddell,ray_jay@aol.com,NaN,300000000,0
13,A06,Led Zeppelin (R),Bob 2,vvqisetnmn0kbl9q,A,Riddell,kannall73@gmail.com,NaN,300000000,0
14,B08,Lynyrd Skynyrd (W),Bob,6nhnbkuqmmwi166w,B,Wilson,kannall73@gmail.com,NaN,300000000,0
15,A07,Meat Loaf (R),Loaf,f21lzl7xmn0kdqo8,A,Riddell,blord20@gmail.com,NaN,300000000,0
16,B09,Meatloaf (W),NT 20,66ao8djmmn0kdqp0,B,Wilson,blord20@gmail.com,NaN,300000000,0
17,B10,Notorious (W),TheChair,brkcyuhbmmyzna5f,B,Wilson,troyad699@gmail.com,troyadavis2019@hotmail.com,300000000,0
18,B12,Post Malone (W),NT 8,i0bvcjk8mo31l0cs,B,Wilson,sergiomiranda78@gmail.com,NaN,300000000,0
19,B11,Run DMC (W),DMC,6wmapyeymntmhosz,B,Wilson,npascucci23@gmail.com,NaN,300000000,0
20,B07,Shredding Terry Kath (W),STK,iud32x7mmpj9c9ev,B,Wilson,lecroy_57@yahoo.com,NaN,300000000,0
21,A11,Spice Girls (R),jordansh,v1xh8wzxmn59uqpa,A,Riddell,jordanshutta@gmail.com,NaN,300000000,0
22,B13,Steel Panther (W),NT 10,886rcw25mo31l0cy,B,Wilson,jnjwuerl@gmail.com,NaN,300000000,0
23,B04,Sting and the CeeDees (W),STCD,va7pi5bimocarcvi,B,Wilson,juventude85@yahoo.com,NaN,300000000,0
24,B14,Brooks and Dunn (W),BD,mvg3okqimod4pn38,B,Wilson,j.milakovich@yahoo.com,NaN,300000000,0
25,A12,Swishahouse (R),KOOPA,j9reafynmn0kbl9m,A,Riddell,lukeep@gmail.com,NaN,300000000,0
26,A13,The Skattmen (R),TSM,bj0zd16smn1ssf8h,A,Riddell,thejaninator4991@gmail.com,frigidaire77@gmail.com,300000000,0
27,A14,Wu-Tang Protection (R),WTP,rzhahbekmmzbhdoj,A,Riddell,ty.mcfadden0692@gmail.com,NaN,300000000,0

## 3 -- Validation

In [4]:
df = pd.read_parquet(DATA / "dim_fantasy_teams.parquet")
print(f"dim_fantasy_teams: {len(df)} rows, {len(df.columns)} columns")
print()

# Team count by conference / division
summary = df.groupby(["conference", "division"]).agg(
    teams=("team_key", "count"),
    missing_email=("manager_email", lambda x: x.isna().sum()),
).reset_index()
print("Teams by conference:")
print(summary.to_string(index=False))
print()

# Full roster display
display_cols = ["team_key", "team_name", "team_abbr", "conference", "division",
                "manager_email", "manager_email_2"]
print("Full team roster:")
print(df[display_cols].to_string(index=False))

dim_fantasy_teams: 28 rows, 10 columns

Teams by conference:
conference division  teams  missing_email
         A  Riddell     14              0
         B   Wilson     14              0

Full team roster:
team_key                 team_name team_abbr conference division              manager_email            manager_email_2
     A09     "National Anthem" (R)  DegenMik          A  Riddell       mvreeland6@gmail.com                        NaN
     A01    AC/DeeCeedeez Nuts (R)  tempfool          A  Riddell      juventude85@yahoo.com                        NaN
     A10                 Big L (R)      BIGL          A  Riddell     benjaninja77@gmail.com                        NaN
     B01     Black Magic Woman (W)       BMW          B   Wilson    justinacain24@gmail.com                        NaN
     A08      Brantley Gilbert (R)  Thebusdr          A  Riddell     j.milakovich@yahoo.com                        NaN
     B02                  Bush (W)      NT 7          B   Wilson        jakeleer@icloud.com                        NaN
     A02          Cyndi Lauper (R)      NT 5          A  Riddell davismelanie1999@gmail.com                        NaN
     B06                Eminem (W)     Shady          B   Wilson              Valkyn KynVal                        NaN
     A03            Flava Flav (R)  Bjuenger          A  Riddell brenden.juengert@gmail.com                        NaN
     B05       Franz Ferdinand (W)        FF          B   Wilson   eduardo.ruizsanz@gmx.com                        NaN
     B03                J Cole (W)      BGFH          B   Wilson     benjaninja77@gmail.com                        NaN
     A04           JETHRO TULL (R)  Thehardw          A  Riddell    travnjazz1221@gmail.com                        NaN
     A05              Kid Rock (R)      K.R.          A  Riddell            ray_jay@aol.com                        NaN
     A06          Led Zeppelin (R)     Bob 2          A  Riddell        kannall73@gmail.com                        NaN
     B08        Lynyrd Skynyrd (W)       Bob          B   Wilson        kannall73@gmail.com                        NaN
     A07             Meat Loaf (R)      Loaf          A  Riddell          blord20@gmail.com                        NaN
     B09              Meatloaf (W)     NT 20          B   Wilson          blord20@gmail.com                        NaN
     B10             Notorious (W)  TheChair          B   Wilson        troyad699@gmail.com troyadavis2019@hotmail.com
     B12           Post Malone (W)      NT 8          B   Wilson  sergiomiranda78@gmail.com                        NaN
     B11               Run DMC (W)       DMC          B   Wilson      npascucci23@gmail.com                        NaN
     B07  Shredding Terry Kath (W)       STK          B   Wilson        lecroy_57@yahoo.com                        NaN
     A11           Spice Girls (R)  jordansh          A  Riddell     jordanshutta@gmail.com                        NaN
     B13         Steel Panther (W)     NT 10          B   Wilson         jnjwuerl@gmail.com                        NaN
     B04 Sting and the CeeDees (W)      STCD          B   Wilson      juventude85@yahoo.com                        NaN
     B14       Brooks and Dunn (W)        BD          B   Wilson     j.milakovich@yahoo.com                        NaN
     A12           Swishahouse (R)     KOOPA          A  Riddell           lukeep@gmail.com                        NaN
     A13          The Skattmen (R)       TSM          A  Riddell thejaninator4991@gmail.com     frigidaire77@gmail.com
     A14    Wu-Tang Protection (R)       WTP          A  Riddell  ty.mcfadden0692@gmail.com                        NaN